### ISSUE TITLE
Disable groups

### ISSUE THREAD

**Issue by yukimuraa** [kenarkose/Settlement#1]
It is possible to disable the functionality of groups? if the json file does not have a group of property the value and not returned, and I need to import a json to use this file.

**Comment by Hyleeh** [comment]
If the setting does not belong to a group, the group property should be left as null.

But as far as I understand, you do not want the group property at all
(Do you have another file you use currently which stores your settings?)

In that case I would suggest processing your JSON file to have the group property as null while importing into Settlement
A simple foreach loop would do the trick:
```php
$settings = json_decode(file_get_contents('your/external/json/settings/file.json'));

foreach($settings as $setting)
{
   settings($setting['key'], $setting['value'], $setting['type']);
}
```

Or maybe you could use the `settings()` method to set multiple settings to Settlement at the same time.

Hope this helps

Also feel free to do a PR :)

**Comment by yukimuraa** [comment]
I began to edit the source code and remove those relating to group and type settings, but just noticing that the error was the comma at the end of an index. Properly indenting the file is read normally.

Thank you for your attention and for the inconvenience.

**Comment by Hyleeh** [comment]
No problem at all!

I am closing the issue now
